import { v4 as uuid } from 'uuid';

export default [
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'ha@gmail.com',
        name: 'Lê Minh Hà',
        sex: 'Nữ',
        age: '28',
        phone: '098234123',
        date: '2019-07-28',
        country: 'Hải Dương',
        status: 'active',
    },
    {
        id: uuid(),
        address: 'Thanh Xuân, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'tu@gmail.com',
        name: 'Lê Phương Tú',
        sex: 'Nam',
        age: '27',
        phone: '098234123',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'inactive',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'inactive',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'tu@gmail.com',
        name: 'Lê Phương Tú',
        age: '24',
        sex: 'Nữ',
        phone: '098234231',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'inactive',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'inactive',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'active',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        country: 'Hải Dương',
        status: 'active',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        country: 'Hải Dương',
        time: '13:08',
        status: 'active',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        country: 'Hải Dương',
        name: 'Lê Phương Nga',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        status: 'active',
    },
    {
        id: uuid(),
        address: 'Đống Đa, Hà Nội',
        avatarUrl: '/static/images/avatars/avatar_3.png',
        // createdAt: 1555016400000,
        email: 'nga@gmail.com',
        name: 'Lê Phương Nga',
        country: 'Hải Dương',
        age: '24',
        sex: 'Nữ',
        phone: '098234345',
        date: '2019-07-28',
        time: '13:08',
        status: 'active',
    },
];

//   address: {
//             country: 'Việt Nam',
//             city: 'Hà Nội',
//             state: 'Thanh Xuân',
//             street: 'Lê Trọng Tấn'
//         },